[package]
name = "host_man"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version="0.12.7", features = ["default", "blocking", "json" ] }
serde = "1.0.208"
tokio = { version = "1.39.3", features = ["full"] }
